platform :ios, ‘8.0’

target 'Noob2017' do

pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 3.0'
pod 'YYModel'
pod 'YYWebImage'
pod 'GTSDK', '~> 1.6.2.0'
pod 'WechatOpenSDK', '~> 1.7.7'
pod 'WeiboSDK', '~> 3.1.3'
pod 'TZImagePickerController', '~> 1.8.1'

end
